### ISSUE TITLE
Call from SNS in serverless.yml

### ISSUE THREAD

**Issue by kylebarron** [kylebarron/landsat-mosaic-latest#1]
https://serverless.com/framework/docs/providers/aws/events/sns#using-a-pre-existing-topic

```yaml
functions:
  dispatcher:
    handler: dispatcher.dispatch
    events:
      - sns: arn:xxx
```
